### ISSUE TITLE
Improved API breadth

### ISSUE THREAD

**Issue by tso** [EugeneLu12/sc2ladder#22]
Perhaps along with the search endpoint we could add in `name` or `bnet` as parameters which replace `query`. So exactly one of `name`, `bnet`, `query` would be required and `race`/`region` would be optional filters.

Along with that I'd love to have more specific APIs such as
`GET /api/player/[realm]/[region]/[id] -> Player`
`GET /api/clans/[clan_name] -> List[Player]`

Any other suggestions for endpoints?

**Comment by jteague9** [comment]
wouldn't `GET /api/player/[realm]/[region]/[id]` need to return a list of players? (each race)

**Comment by tso** [comment]
yep you're right, good clarification
